<a href="https://colab.research.google.com/github/Ganeshkumar-1358/ai-ml/blob/main/part1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#inserting element in list
import numpy as np
a = int(input("Enter a number: "))
b = [1, 2, 3, 4, 5]
b.append(a)
print(b)
#inserting element in array
import numpy as np
a = int(input("Enter a number: "))
b = np.array([1, 2, 3, 4, 5])
b_list = b.tolist()
b_list.append(a)
b = np.array(b_list)
print(b)
#type
A = "Hello, world!"
variable = 42
float= 3.14
list = [1, 2, 3]
array = np.array([1, 2, 3])
print("Type of string_variable:", type(A))
print("Type of variable:", type(variable))
print("Type of float:", type(float_variable))
print("Type of list:", type(list_variable))
print("Type of array:", type(array_variable))
# Check if each variable is a string
print("Is A a string?", isinstance(A, str))
print("Is variable a string?", isinstance(variable, str))
print("Is float a string?", isinstance(float, str))
print("Is list a string?", isinstance(list, str))
print("Is array a string?", isinstance(array, str))
# Scalar values
a = int(input("Enter a number: "))
b = int(input("Enter a number: "))
mul_result = a * b
print(f"{a} * {b} = {mul_result}")
div_result = a / b
print(f"{a} / {b} = {div_result}")
pow_result = a ** b
print(f"{a} ** {b} = {pow_result}")
#Array
import numpy as np
arr1 = np.array([2, 4, 6])
arr2 = np.array([1, 2, 3])
mul_result_arr = arr1 * arr2
print(f"Array multiplication:\n{arr1} * {arr2} = {mul_result_arr}")
div_result_arr = arr1 / arr2
print(f"Array division:\n{arr1} / {arr2} = {div_result_arr}")
pow_result_arr = arr1 ** arr2
print(f"Array exponentiation:\n{arr1} ** {arr2} = {pow_result_arr}")
#implement
import numpy as np
x = 2.0
sin_x = np.sin(x)
print(f"sin({x}) = {sin_x}")
log_x = np.log(x)
print(f"log({x}) = {log_x}")
log2_x = np.log2(x)
print(f"log2({x}) = {log2_x}")
exp_x = np.exp(x)
print(f"exp({x}) = {exp_x}")
import numpy as np
arr = np.array([1, 2, 3, 4])
sin_arr = np.sin(arr)
print(f"sin({arr}) = {sin_arr}")
log_arr = np.log(arr)
print(f"log({arr}) = {log_arr}")
log2_arr = np.log2(arr)
print(f"log2({arr}) = {log2_arr}")
exp_arr = np.exp(arr)
print(f"exp({arr}) = {exp_arr}")


Enter a number: 22
[1, 2, 3, 4, 5, 22]
Enter a number: 33
[ 1  2  3  4  5 33]
Type of string_variable: <class 'str'>
Type of variable: <class 'int'>
Type of float: <class 'float'>
Type of list: <class 'list'>
Type of array: <class 'numpy.ndarray'>
Is A a string? True
Is variable a string? False
Is float a string? False
Is list a string? False
Is array a string? False
Enter a number: 4
Enter a number: 4
4 * 4 = 16
4 / 4 = 1.0
4 ** 4 = 256
Array multiplication:
[2 4 6] * [1 2 3] = [ 2  8 18]
Array division:
[2 4 6] / [1 2 3] = [2. 2. 2.]
Array exponentiation:
[2 4 6] ** [1 2 3] = [  2  16 216]
sin(2.0) = 0.9092974268256817
log(2.0) = 0.6931471805599453
log2(2.0) = 1.0
exp(2.0) = 7.38905609893065
sin([1 2 3 4]) = [ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
log([1 2 3 4]) = [0.         0.69314718 1.09861229 1.38629436]
log2([1 2 3 4]) = [0.        1.        1.5849625 2.       ]
exp([1 2 3 4]) = [ 2.71828183  7.3890561  20.08553692 54.59815003]
